### PR TITLE
fix completed anime eps count (parallel calls)

### PR DESCRIPTION
**Pull request by sudoAlphaX**
used grequests to parallelly ask the mal api for total episodes count.

### CODE REVIEW

**Comment by sudoAlphaX** [comment]
After a benchmarking test, it takes an average of 20 seconds for 100 get requests, no matter the parallel call count. I think it would be better to use 10 to 20 parallel calls to avoid rate limiting.

**Comment by sudoAlphaX** [comment]
Benchmark reports:

Start Benchmark test:

100 calls completed with 5 calls in parallel in 25.6838 seconds
100 calls completed with 10 calls in parallel in 22.4837 seconds
100 calls completed with 20 calls in parallel in 21.7854 seconds
100 calls completed with 25 calls in parallel in 21.7158 seconds
100 calls completed with 30 calls in parallel in 21.8709 seconds
100 calls completed with 50 calls in parallel in 22.0290 seconds

**Comment by Zai-Kun** [comment]
After doing some tests, I've found that your implementation takes about 35-40 seconds for 144 requests, whereas my version only takes around 10-15 seconds for the same 144 requests with the same number of parallel calls (10).

**Comment by sudoAlphaX** [comment]
Thats true. I tested it just now, and it takes about 40 seconds. Yes, my implementation is not very effective. I hope I could learn from your code.

BTW, I'm currently spamming the api to hit the rate limit. I will tell you the error to handle soon.

**Comment by sudoAlphaX** [comment]
image

image

It seems that it returns the usual response 200 on successful GET request. But sometime, it returns none, I think it might be the rate limiting, or it may also be due to my client sided issues. Ill test it a little more and let you know.

**Comment by Zai-Kun** [comment]
> image
> 
> image
> 
> It seems that it returns the usual response 200 on successful GET request. But sometime, it returns none, I think it might be the rate limiting, or it may also be due to my client sided issues. Ill test it a little more and let you know.

I see, we should just put -1 if it returns None then. I'm also going to spam the API with requests to gather more information on it.

**Comment by sudoAlphaX** [comment]
Alright, I have a discovery:
image

so, I had it to make a new request when it is none and this is what i received:
image

So it returns a response 403

[Mozilla Response 403 Info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)

[Wikipedia Info](https://en.wikipedia.org/wiki/HTTP_403)

> [HTTP](https://en.wikipedia.org/wiki/HTTP_404) 403 is an HTTP status code meaning access to the requested resource is forbidden. The server understood the request, but will not fulfill it, if it was correct.

Its a Forbidden error. So I think that might be the rate limit.

**Comment by Zai-Kun** [comment]
After spamming the API for a while, it returned this:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: I6rUNaK2Nxs2Rf3Yuxe8fDX2OyVvzlqwzHwHJpYf37ekYXeDFaG57Q==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by Zai-Kun** [comment]
> Alright, I have a discovery: image
> 
> so, I had it to make a new request when it is none and this is what i received: image
> 
> So it returns a response 403
> 
> [Mozilla Response 403 Info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)
> 
> [Wikipedia Info](https://en.wikipedia.org/wiki/HTTP_403)
> 
> > [HTTP](https://en.wikipedia.org/wiki/HTTP_404) 403 is an HTTP status code meaning access to the requested resource is forbidden. The server understood the request, but will not fulfill it, if it was correct.
> 
> Its a Forbidden error. So I think that might be the rate limit.

Yup, so what should we do about this? Should we replace it with -1?

**Comment by sudoAlphaX** [comment]
> I see, we should just put -1 if it returns None then. I'm also going to spam the API with requests to gather more information on it.

Does -1 work? I dont think -1 updated anything when I tried it (long ago when I used the tool to import my aniwatch list to mal). Let me try it now.

**Comment by sudoAlphaX** [comment]
image

Another confirmation that 403 is indeed rate limiting

**Comment by Zai-Kun** [comment]
> > I see, we should just put -1 if it returns None then. I'm also going to spam the API with requests to gather more information on it.
> 
> Does -1 work? I dont think -1 updated anything when I tried it (long ago when I used the tool to import my aniwatch list to mal). Let me try it now.

I will try it too then.

**Comment by sudoAlphaX** [comment]
Nope, -1 doesn't do anything

image

Using a value greater than 0 updates it, so it's not syntax error:

image

**Comment by Zai-Kun** [comment]
> Nope, -1 doesn't do anything
> 
> image

Same here. I could have sworn it used to work. Maybe they changed their API.

**Comment by Zai-Kun** [comment]
Another thing, I set my status to "Complete," but when I open the same anime on MAL, it says "Watching." It returned this though:

```json
{"status":"completed","score":0,"num_episodes_watched":0,"is_rewatching":false,"updated_at":"2023-10-21T19:22:06+00:00","priority":0,"num_times_rewatched":0,"rewatch_value":0,"tags":[],"comments":""}
```

**Comment by sudoAlphaX** [comment]
It wasn't like this before. Cause it worked for me 2 or 3 weeks ago when I used the tool.
Truly, this API is a mystery.

**Comment by sudoAlphaX** [comment]
I found out a simple trick. No need to fetch anything from the server.

image

But why is this set as Watching when it returned completed?
image

**Comment by sudoAlphaX** [comment]
> Another thing, I set my status to "Complete," but when I open the same anime on MAL, it says "Watching." It returned this though:
> 
> ```json
> {"status":"completed","score":0,"num_episodes_watched":0,"is_rewatching":false,"updated_at":"2023-10-21T19:22:06+00:00","priority":0,"num_times_rewatched":0,"rewatch_value":0,"tags":[],"comments":""}
> ```

By the way, I think that is an issue on the MAL anime page. Because on the anime list, it shows completed:

image

Same case with the export also:
image

**Comment by Zai-Kun** [comment]
> I found out a simple trick. No need to fetch anything from the server.
> 
> image
> 
> But why is this set as Watching when it returned completed? image

Oh, good idea! We can set it to a really large number.

**Comment by Zai-Kun** [comment]
Now, for the second problem, why isn't it setting it as completed?

**Comment by sudoAlphaX** [comment]
Well, 3 pull requests for nothing. Happy that a solution is obtained though. It was fun debugging with you @Zai-Kun

**Comment by Zai-Kun** [comment]
> Well, 3 pull requests for nothing. Happy that a solution is obtained though. It was fun debugging with you @Zai-Kun

It was for me too. I'd love to work on new projects with you.

**Comment by sudoAlphaX** [comment]
It is setting as completed, its just that the particular MAL page which has the anime details doesnt show it.
The API returned completed, and it is also marked as completed in the [Anime List](https://myanimelist.net/animelist/). Just to confirm, I exported my anime list, and its the same.

image

So I think its some server-sided problem.

**Comment by Zai-Kun** [comment]
> It is setting as completed, its just that the particular MAL page which has the anime details doesnt show it. The API returned completed, and it is also marked as completed in the [Anime List](https://myanimelist.net/animelist/). Just to confirm, I exported my anime list, and its the same.
> 
> image
> 
> So I think its some server-sided problem.

Oh, I see. Thanks for the help.

**Comment by sudoAlphaX** [comment]
May I close this PR?

**Comment by Zai-Kun** [comment]
> May I close this PR?

Yeah, do it.

**Comment by sudoAlphaX** [comment]
Nice working with you @Zai-Kun

**Pull request closed without merging**
