### PR TITLE
Revert "Fix completed anime episode count"

### PR DESCRIPTION
**Pull request by Zai-Kun**
Reverts Zai-Kun/AniWatch-AKA-Zoro-To-MyAnimeList#1

Sending a GET request to retrieve the total EPS significantly slowed it down. Moreover, using -1 appears to work just fine. Therefore, I'm going to revert the pull request.

### CODE REVIEW

**Comment by sudoAlphaX** [comment]
Actually, adding -1 didnt seem to work for me. I have over 100 completed anime and I had to open each mal link from the json file to update the completed status. Can I rewrite it to fetch the total episode count of all completed animes before and save it to a variable, then use it to update it. That way, all the get requests will be done together before mal update api request.

**Comment by Zai-Kun** [comment]
> Actually, adding -1 didnt seem to work for me. I have over 100 completed anime and I had to open each mal link from the json file to update the completed status. Can I rewrite it to fetch the total episode count of all completed animes before and save it to a variable, then use it to update it. That way, all the get requests will be done together before mal update api request.


yeah, that sounds cool. If you can, make it async and set the limit to around 15-20 requests at a time.

I can handle it myself if you're not sure how to.

**Comment by sudoAlphaX** [comment]
alright, ill try to implement that

**Comment by Zai-Kun** [comment]
@sudoAlphaX  I've finished my implementation, but I haven't tested it yet. Here's the code:



```python
import asyncio, aiohttp

async def FETCH_ANIME_TOTAL_EPISODES(anime_id, session, sema):
    url = f"https://api.myanimelist.net/v2/anime/{anime_id}?fields=num_episodes"

    async with sema:
        async with session.get(url) as response:
            json_response = await response.json()
            return json_response["num_episodes"]

async def FETCH_TOTAL_EPISODES_FOR_MULTIPLE_ANIME(anime_ids, session):
    total_episodes = {}

    sema = asyncio.BoundedSemaphore(15)
    tasks = [FETCH_ANIME_TOTAL_EPISODES(anime_id, session, sema) for anime_id in anime_ids]
    results = await asyncio.gather(*tasks)
 
    total_episodes = dict(zip(anime_ids, results))

    return total_episodes


async def _ASYNC_EXPORT_TO_MAL(API_KEY, ID, watchlist_zoro):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/x-www-form-urlencoded"
    }

    convert = {
        'On-Hold': 'on_hold',
        'Completed': 'completed',
        'Plan to watch': 'plan_to_watch',
        'Dropped': 'dropped',
        'Watching': 'watching',
    }

    total_anime = 0
    total_anime_added = 0

    completed_anime_ids = []
    
    for status in watchlist_zoro.keys():
        total_anime += len(watchlist_zoro[status])
        if status == "Completed":
            for anime in watchlist_zoro[status]:
                anime_id = anime["link"].split("/")[-1] # example link: https://myanimelist.net/anime/5114
                completed_anime_ids.append(anime_id)
    
    async with aiohttp.ClientSession(headers=headers) as session:
        results = await FETCH_TOTAL_EPISODES_FOR_MULTIPLE_ANIME(anime_ids, session)

        for status in watchlist_zoro.keys():
            for anime in watchlist_zoro[status]:

                anime_id = anime["link"].split("/")[-1]
                url = f"https://api.myanimelist.net/v2/anime/{anime_id}/my_list_status"
                payload = {"status": convert[status]}

                if status == 'Completed':
                    payload["num_watched_episodes"] = results[anime_id]

                response = await session.put(url,
                                        headers=headers,
                                        data=urlencode(payload))
                if not response.ok:
                    with open("error_logs", "a") as f:
                        f.write(f"Error adding anime to the watchlist of {ID}: {response.text}\nPayload: {payload}\nURL: {url}")

                total_anime_added += 1
                progress.UPDATE_PROGRESS(
                    ID, TO_PERCENTAGE(total_anime_added, total_anime))


def EXPORT_TO_MAL(API_KEY, ID, watchlist_zoro):
    asyncio.run(_ASYNC_EXPORT_TO_MAL(API_KEY, ID, watchlist_zoro))
```
If you have a better implementation, please send a pull request.

**Comment by sudoAlphaX** [comment]
Sure. I'm using grequests. I'm currently running benchmarking for various counts of parallel calls. Will send a PR soon.

**Comment by sudoAlphaX** [comment]
In my opinion, your implementation is better than mine. I am not well-versed in async functions, so I used grequests. Moreover, I was unable to get aiohttp installed on my machine. And make sure to add error handling for get requests. I got an error due to spamming about 600 calls in a span of 5 minutes.

**Comment by Zai-Kun** [comment]
> In my opinion, your implementation is better than mine. I am not well-versed in async functions, so I used grequests. Moreover, I was unable to get aiohttp installed on my machine. And make sure to add error handling for get requests. I got an error due to spamming about 600 calls in a span of 5 minutes.

Ah, thanks for the info. Could you please let me know what error message you received from the server?

**Pull request merged**
